highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://yuang-ian.github.io/vitae
author: Yuang Shi

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Yuang Shi's Resume
name: Yuang Shi
email: yuangshi@u.nus.edu
email_full: mailto:yuangshi@u.nus.edu
website: Homepage
website_full: https://yuang-ian.github.io/
github: Shiyuang-scu
twitter: YoI1ZRL7iDJf2xx
# tel: +44 0000 000000
# tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/CaLE2wcq3y8chyKo8'
address:
  street: COM1, 13, Computing Drive
  postcode: 117417
  city: Singapore
  # country: Singapore
google_analytics: UA-143142181-1

# needed for travis-ci build
exclude: [vendor]
